# This is the combination of many playbooks that will hopefully take a fresh
# install of Raspbian and setup all necessary components of it to function in
# the swarm.

- import_playbook: setup-hostnames.yaml
- import_playbook: setup-ssh.yaml
- import_playbook: update-packages.yaml
- import_playbook: setup-docker.yaml